sudo: required
language: cpp
services:
- docker
env:
- DOVECOT="release-2.2.21"
before_install:
- docker network create --driver=bridge --subnet=192.168.100.0/24 --gateway=192.168.100.1 ceph_network
- travis_wait 30 docker run -itd --name build --net=ceph_network -e SOURCE_VERSION=$DOVECOT -v $(pwd):/repo cephdovecot/travis-build:$DOVECOT sh
- docker exec build sh -c 'printf "nameserver 8.8.8.8\n" > /etc/resolv.conf'
- docker exec build apt-get -qq update
- docker exec build apt-get -qq upgrade
- docker exec build DEBIAN_FRONTEND=noninteractive apt-get install -qq -q librdkafka-dev
before_script:
- docker exec build sh -c 'cd /usr/local/src/dovecot; git pull origin $SOURCE_VERSION'
- docker exec build sh -c 'cd /usr/local/src/dovecot; make install'
script:
- docker exec build sh -c 'cd repo; ./autogen.sh'
- docker exec build sh -c 'cd repo; ./configure --with-dovecot=/usr/local/lib/dovecot --enable-valgrind --enable-debug --enable-maintainer-mode'
- docker exec build sh -c 'cd repo; make clean install'
- docker exec build sh -c 'ldconfig'
- docker exec build sh -c 'cd repo; src/test-kafka-event'

after_script:
- docker stop build
- docker rm build
- docker network rm ceph_network

